Sid

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -9,15 +9,16 @@ BUILD_DIR=$1
 DOWNLOAD_URL="https://phpstack-896782-3112621.cloudwaysapps.com/ffmpeg.tar.xz"
 echo "       DOWNLOAD_URL = ${DOWNLOAD_URL}"
 
-cd $BUILD_DIR
-mkdir vendor
-cd vendor
-mkdir ffmpeg
-curl -L --silent $DOWNLOAD_URL | tar -Jx --strip-components=1 -C ffmpeg/
+# Navigate to the build directory
+cd $BUILD_DIR || { echo "Error navigating to BUILD_DIR"; exit 1; }
 
-# let's configure the path and make ffmpeg usable
+# Create necessary directories
+mkdir -p vendor/ffmpeg
 
-echo "       exporting PATH"
+# Download and extract ffmpeg
+echo "       Downloading and extracting ffmpeg..."
+curl -L --silent $DOWNLOAD_URL | tar -Jx --strip-components=1 -C vendor/ffmpeg/ || { echo "Error downloading or extracting ffmpeg"; exit 1; }
+
+echo "       Configuring PATH..."
 PROFILE_PATH="${BUILD_DIR}/.profile.d/ffmpeg.sh"
-mkdir -p "${BUILD_DIR}/.profile.d/"
-echo 'export PATH="/app/vendor/ffmpeg:$PATH"' >> $PROFILE_PATH
+echo 'export PATH="/app/vendor/ffmpeg:$PATH"' > $PROFILE_PATH
