ss

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -10,7 +10,7 @@ DOWNLOAD_URL="https://phpstack-896782-3112621.cloudwaysapps.com/ffmpeg-amd64.zip
 echo "       DOWNLOAD_URL = ${DOWNLOAD_URL}"
 
 # Navigate to the build directory
-cd $BUILD_DIR || { echo "Error navigating to BUILD_DIR"; exit 1; }
+# cd $BUILD_DIR || { echo "Error navigating to BUILD_DIR"; exit 1; }
 
 # Create necessary directories
 mkdir -p vendor/ffmpeg
@@ -22,7 +22,7 @@ curl -L --silent -o ffmpeg.zip $DOWNLOAD_URL
 
 # Unzip ffmpeg
 echo "       Unzipping ffmpeg..."
-# unzip -q ffmpeg.zip -d vendor/ffmpeg/ || { echo "Error unzipping ffmpeg"; exit 1; }
+unzip -q ffmpeg.zip -d vendor/ffmpeg/ || { echo "Error unzipping ffmpeg"; exit 1; }
 
 # Optionally remove the downloaded zip file to clean up space
 rm ffmpeg.zip
