ss

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -20,9 +20,9 @@ mkdir -p vendor/ffmpeg
 echo "       Downloading ffmpeg..."
 curl -L --silent -o ffmpeg.zip $DOWNLOAD_URL 
 
-# Unzip ffmpeg
-echo "       Unzipping ffmpeg..."
-unzip -q ffmpeg.zip -d vendor/ffmpeg/ || { echo "Error unzipping ffmpeg"; exit 1; }
+# # Unzip ffmpeg
+# echo "       Unzipping ffmpeg..."
+# unzip -q ffmpeg.zip -d vendor/ffmpeg/ || { echo "Error unzipping ffmpeg"; exit 1; }
 
 # Optionally remove the downloaded zip file to clean up space
 rm ffmpeg.zip
